// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6OyzZf7PCdrCifsfbmRF1MCf-j2o_3M',
    appId: '1:515271807716:web:4efdfb35861dbd8ba952f1',
    messagingSenderId: '515271807716',
    projectId: 'connect--call1',
    authDomain: 'connect--call1.firebaseapp.com',
    storageBucket: 'connect--call1.firebasestorage.app',
    measurementId: 'G-3GQ3LLGJ0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDd7ECKwvw8fYnyzDq6sXXzf7fw8Zd2jQ',
    appId: '1:515271807716:android:8bd9b2a8cebedcd7a952f1',
    messagingSenderId: '515271807716',
    projectId: 'connect--call1',
    storageBucket: 'connect--call1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwO4IZATcRvrDuR3g1bMKWxffE4Y6bhU',
    appId: '1:515271807716:ios:d4f5e2c0aa7f1465a952f1',
    messagingSenderId: '515271807716',
    projectId: 'connect--call1',
    storageBucket: 'connect--call1.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiwO4IZATcRvrDuR3g1bMKWxffE4Y6bhU',
    appId: '1:515271807716:ios:d4f5e2c0aa7f1465a952f1',
    messagingSenderId: '515271807716',
    projectId: 'connect--call1',
    storageBucket: 'connect--call1.firebasestorage.app',
    iosBundleId: 'com.example.connectcall',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm6OyzZf7PCdrCifsfbmRF1MCf-j2o_3M',
    appId: '1:515271807716:web:3f0661fe80697828a952f1',
    messagingSenderId: '515271807716',
    projectId: 'connect--call1',
    authDomain: 'connect--call1.firebaseapp.com',
    storageBucket: 'connect--call1.firebasestorage.app',
    measurementId: 'G-VZX5Q9C1QX',
  );
}
